all:sorter

sorter: global.h mergesort.h record.h recordarray.h sortingkey.h tokenizer.h sorter.h helper.h mergesort.c record.c recordarray.c sortingkey.c tokenizer.c sorter.c helper.c
	gcc -Wall -Werror -fsanitize=address -lm mergesort.c record.c recordarray.c sortingkey.c tokenizer.c sorter.c helper.c -o sorter

clean:
	rm -rf sorter 





	
	


			   





			   